name: meal_mate
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  localization: ^2.1.0
  cupertino_icons: ^1.0.2
  google_fonts: ^6.2.1
  font_awesome_flutter: ^10.2.1
  provider: ^6.0.1
  flutter_spinkit: ^5.1.0
  animated_splash_screen: ^1.3.0
  firebase_auth: ^4.19.6
  get: ^4.6.5
  country_icons: ^2.0.2
  camera:
  path_provider:
  path:
  image_picker: ^1.1.0
  firebase_core: ^2.30.0
  firebase_storage: ^11.7.2
  cloud_firestore: ^4.9.1
  flutter_screenutil: ^5.5.3+2
  page_transition: ^2.0.9
  smooth_page_indicator: ^1.0.0+2
  shimmer_animation: ^2.1.0+1
  animated_text_kit: ^4.2.2
  intl: ^0.18.1
  delayed_display: ^2.0.0
  firebase_auth_platform_interface: ^7.2.3
  country_picker: ^2.0.16
  percent_indicator: ^4.2.2
  intl_phone_number_input: ^0.7.0+2
  image: ^4.0.17
  carousel_slider: ^4.1.1
  auto_size_text: ^3.0.0
  lottie: ^3.0.0
  mask_text_input_formatter: ^2.4.0
  flutter_advanced_drawer: ^1.3.2
  shared_preferences: ^2.0.20
  url_launcher: ^6.1.7
  file_picker: ^8.0.1
  open_file_plus: ^3.3.0
  rive: ^0.13.1
  cloud_functions: ^4.0.11
  http: ^1.2.1
  firebase_messaging: ^14.6.7
  flutter_native_splash: ^2.3.6
  flutter_animate: ^4.1.1+1
  shimmer: ^3.0.0
  flutter_icons_helper: ^0.0.5
  local_auth: ^2.1.7
  another_stepper: ^1.2.2 
  flutter_svg: ^2.0.6
  internet_connection_checker: ^1.0.0+1
  connectivity_plus: ^6.0.3
  internet_connection_checker_plus: ^2.3.0
  dio: ^5.2.1+1
  schedulers: ^1.0.1
  voice_message_package: ^2.1.4
  audioplayers: ^6.0.0
  just_audio: ^0.9.34
  flutter_typeahead: ^5.2.0
  google_maps_flutter: ^2.6.1
  pdf: ^3.10.4
  firebase_crashlytics: ^3.3.4
  firebase_analytics: ^10.4.4
  get_it: ^7.6.0
  showcaseview: ^3.0.0
  process_run: ^0.14.2
  progressive_image: ^2.0.1
  google_sign_in: ^6.1.5
  animations: ^2.0.8
  google_nav_bar: ^5.0.6
  popover: ^0.3.0
  flutter_slidable: ^3.0.0
  flutter_libphonenumber: ^2.1.5
  firebase_app_check: ^0.2.0+1
  gap: ^3.0.1
  table_calendar: ^3.0.9
  flutter_time_picker_spinner: ^2.0.0
  flutter_rating_bar: ^4.0.1
  geolocator: ^12.0.0
  flutter_markdown: ^0.7.0
  fl_chart: ^0.68.0
  flutter_windowmanager: ^0.2.0
  secure_application: ^4.0.1
  badges: ^3.1.2
  page_view_dot_indicator: ^2.3.0
  flutter_facebook_auth: ^7.0.0
  expandable: ^5.0.1
  expandable_text: ^2.3.0
  device_info_plus: ^10.1.0
  multi_select_flutter: ^4.1.3
  flutter_multi_select_form_field: ^0.0.1
  flutter_sticky_header: ^0.6.5
  marquee: ^2.2.3
  package_info_plus: ^8.0.0
  speech_to_text: ^6.6.0
  permission_handler: ^11.2.0
  firebase_performance: ^0.9.2+7
  step_progress_indicator: ^1.0.2
  google_generative_ai: ^0.4.0
  twilio_flutter: ^0.3.0
  google_places_flutter: ^2.0.8
  supabase_flutter: ^2.5.4
  flutter_gemini: ^2.0.4
  flutter_keyboard_visibility: ^6.0.0
  logger: ^2.3.0
  intl_phone_field: ^3.2.0
  firebase_remote_config: ^4.4.7
  googleapis_auth: ^1.6.0
  googleapis: ^13.1.0
  syncfusion_flutter_gauges: ^25.2.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/logo/
    - assets/lotties/
  
  fonts:
    - family: Comfortaa
      fonts:
        - asset: fonts/Comfortaa-VariableFont_wght.ttf
    - family: Omnes
      fonts:
        - asset: fonts/Omnes-Regular.ttf
        - asset: fonts/Omnes-Bold.ttf
          weight: 700
        - asset: fonts/Omnes-Italic.ttf
          style: italic
        - asset: fonts/Omnes-BoldItalic.ttf
          weight: 700
          style: italic


flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo/logo_launch.png"
  min_sdk_android: 23